;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWGN2
inhook 3  
tuck - f48 3 
tuck - f44 3 
tuck - f40 3 
tuck - f36 3 
tuck - f32 3 
tuck - f28 3 
tuck - f24 3 
tuck - f20 3 
tuck - f16 3 
tuck - f12 3 
tuck - f8 3 
tuck - f4 3 
tuck + b1 3 
tuck + b5 3 
tuck + b9 3 
tuck + b13 3 
tuck + b17 3 
tuck + b21 3 
tuck + b25 3 
tuck + b29 3 
tuck + b33 3 
tuck + b37 3 
tuck + b41 3 
tuck + b45 3 
tuck - f46 3 
tuck - f42 3 
tuck - f38 3 
tuck - f34 3 
tuck - f30 3 
tuck - f26 3 
tuck - f22 3 
tuck - f18 3 
tuck - f14 3 
tuck - f10 3 
tuck - f6 3 
tuck - f2 3 
tuck + b3 3 
tuck + b7 3 
tuck + b11 3 
tuck + b15 3 
tuck + b19 3 
tuck + b23 3 
tuck + b27 3 
tuck + b31 3 
tuck + b35 3 
tuck + b39 3 
tuck + b43 3 
tuck + b47 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
releasehook 3  
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer f1 b1 
xfer f2 b2 
xfer f3 b3 
xfer f4 b4 
xfer f5 b5 
xfer f6 b6 
xfer f7 b7 
xfer f8 b8 
xfer f9 b9 
xfer f10 b10 
xfer f11 b11 
xfer f12 b12 
xfer f13 b13 
xfer f14 b14 
rack -2
xfer f14 b16 
xfer f15 b17 
xfer f16 b18 
xfer f17 b19 
xfer f18 b20 
xfer f19 b21 
xfer f20 b22 
xfer f21 b23 
xfer f22 b24 
xfer f23 b25 
xfer f24 b26 
xfer f25 b27 
xfer f26 b28 
xfer f27 b29 
xfer f28 b30 
xfer f29 b31 
xfer f30 b32 
xfer f31 b33 
xfer f32 b34 
xfer f33 b35 
xfer f34 b36 
xfer f35 b37 
xfer f36 b38 
xfer f37 b39 
xfer f38 b40 
xfer f39 b41 
xfer f40 b42 
xfer f41 b43 
xfer f42 b44 
xfer f43 b45 
xfer f44 b46 
xfer f45 b47 
xfer f46 b48 
xfer f47 b49 
xfer f48 b50 
xfer f49 b51 
xfer f50 b52 
rack 0
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer f1 b1 
xfer f2 b2 
xfer f3 b3 
xfer f4 b4 
xfer f5 b5 
xfer f6 b6 
xfer f7 b7 
xfer f8 b8 
xfer f9 b9 
xfer f10 b10 
xfer f11 b11 
xfer f12 b12 
xfer f13 b13 
xfer f14 b14 
xfer f15 b15 
xfer f16 b16 
xfer f17 b17 
xfer f18 b18 
xfer f19 b19 
xfer f20 b20 
xfer f21 b21 
xfer f22 b22 
xfer f23 b23 
xfer f24 b24 
xfer f25 b25 
xfer f26 b26 
xfer f27 b27 
xfer f28 b28 
rack -2
xfer f28 b30 
xfer f29 b31 
xfer f30 b32 
xfer f31 b33 
xfer f32 b34 
xfer f33 b35 
xfer f34 b36 
xfer f35 b37 
xfer f36 b38 
xfer f37 b39 
xfer f38 b40 
xfer f39 b41 
xfer f40 b42 
xfer f41 b43 
xfer f42 b44 
xfer f43 b45 
xfer f44 b46 
xfer f45 b47 
xfer f46 b48 
xfer f47 b49 
xfer f48 b50 
xfer f49 b51 
xfer f50 b52 
xfer f51 b53 
xfer f52 b54 
rack 0
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer f1 b1 
xfer f2 b2 
xfer f3 b3 
xfer f4 b4 
xfer f5 b5 
xfer f6 b6 
xfer f7 b7 
xfer f8 b8 
xfer f9 b9 
xfer f10 b10 
xfer f11 b11 
xfer f12 b12 
xfer f13 b13 
xfer f14 b14 
xfer f15 b15 
xfer f16 b16 
xfer f17 b17 
xfer f18 b18 
xfer f19 b19 
xfer f20 b20 
xfer f21 b21 
xfer f22 b22 
xfer f23 b23 
xfer f24 b24 
xfer f25 b25 
xfer f26 b26 
xfer f27 b27 
xfer f28 b28 
xfer f29 b29 
xfer f30 b30 
xfer f31 b31 
xfer f32 b32 
xfer f33 b33 
xfer f34 b34 
xfer f35 b35 
xfer f36 b36 
xfer f37 b37 
xfer f38 b38 
xfer f39 b39 
xfer f40 b40 
xfer f41 b41 
xfer f42 b42 
rack -2
xfer f42 b44 
xfer f43 b45 
xfer f44 b46 
xfer f45 b47 
xfer f46 b48 
xfer f47 b49 
xfer f48 b50 
xfer f49 b51 
xfer f50 b52 
xfer f51 b53 
xfer f52 b54 
xfer f53 b55 
xfer f54 b56 
rack 0
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer f1 b1 
xfer f2 b2 
xfer f3 b3 
xfer f4 b4 
xfer f5 b5 
xfer f6 b6 
xfer f7 b7 
xfer f8 b8 
xfer f9 b9 
xfer f10 b10 
xfer f11 b11 
xfer f12 b12 
xfer f13 b13 
xfer f14 b14 
xfer f15 b15 
xfer f16 b16 
xfer f17 b17 
xfer f18 b18 
xfer f19 b19 
xfer f20 b20 
xfer f21 b21 
xfer f22 b22 
xfer f23 b23 
xfer f24 b24 
xfer f25 b25 
xfer f26 b26 
xfer f27 b27 
xfer f28 b28 
xfer f29 b29 
xfer f30 b30 
xfer f31 b31 
xfer f32 b32 
xfer f33 b33 
xfer f34 b34 
xfer f35 b35 
xfer f36 b36 
xfer f37 b37 
xfer f38 b38 
xfer f39 b39 
xfer f40 b40 
xfer f41 b41 
xfer f42 b42 
xfer f43 b43 
xfer f44 b44 
xfer f45 b45 
xfer f46 b46 
xfer f47 b47 
xfer f48 b48 
xfer f49 b49 
xfer f50 b50 
xfer f51 b51 
xfer f52 b52 
xfer f53 b53 
xfer f54 b54 
xfer f55 b55 
xfer f56 b56 
rack -2
xfer f56 b58 
rack 0
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer f1 b1 
xfer f2 b2 
xfer f3 b3 
xfer f4 b4 
xfer f5 b5 
xfer f6 b6 
xfer f7 b7 
xfer f8 b8 
xfer f9 b9 
xfer f10 b10 
xfer f11 b11 
xfer f12 b12 
xfer f13 b13 
xfer f14 b14 
xfer f15 b15 
xfer f16 b16 
rack -2
xfer f16 b18 
xfer f17 b19 
xfer f18 b20 
xfer f19 b21 
xfer f20 b22 
xfer f21 b23 
xfer f22 b24 
xfer f23 b25 
xfer f24 b26 
xfer f25 b27 
xfer f26 b28 
xfer f27 b29 
xfer f28 b30 
xfer f29 b31 
xfer f30 b32 
xfer f31 b33 
xfer f32 b34 
xfer f33 b35 
xfer f34 b36 
xfer f35 b37 
xfer f36 b38 
xfer f37 b39 
xfer f38 b40 
xfer f39 b41 
xfer f40 b42 
xfer f41 b43 
xfer f42 b44 
xfer f43 b45 
xfer f44 b46 
xfer f45 b47 
xfer f46 b48 
xfer f47 b49 
xfer f48 b50 
xfer f49 b51 
xfer f50 b52 
xfer f51 b53 
xfer f52 b54 
xfer f53 b55 
xfer f54 b56 
xfer f55 b57 
xfer f56 b58 
xfer f57 b59 
xfer f58 b60 
rack 0
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer f1 b1 
xfer f2 b2 
xfer f3 b3 
xfer f4 b4 
xfer f5 b5 
xfer f6 b6 
xfer f7 b7 
xfer f8 b8 
xfer f9 b9 
xfer f10 b10 
xfer f11 b11 
xfer f12 b12 
xfer f13 b13 
xfer f14 b14 
xfer f15 b15 
xfer f16 b16 
xfer f17 b17 
xfer f18 b18 
xfer f19 b19 
xfer f20 b20 
xfer f21 b21 
xfer f22 b22 
xfer f23 b23 
xfer f24 b24 
xfer f25 b25 
xfer f26 b26 
xfer f27 b27 
xfer f28 b28 
xfer f29 b29 
xfer f30 b30 
xfer f31 b31 
xfer f32 b32 
rack -2
xfer f32 b34 
xfer f33 b35 
xfer f34 b36 
xfer f35 b37 
xfer f36 b38 
xfer f37 b39 
xfer f38 b40 
xfer f39 b41 
xfer f40 b42 
xfer f41 b43 
xfer f42 b44 
xfer f43 b45 
xfer f44 b46 
xfer f45 b47 
xfer f46 b48 
xfer f47 b49 
xfer f48 b50 
xfer f49 b51 
xfer f50 b52 
xfer f51 b53 
xfer f52 b54 
xfer f53 b55 
xfer f54 b56 
xfer f55 b57 
xfer f56 b58 
xfer f57 b59 
xfer f58 b60 
xfer f59 b61 
xfer f60 b62 
rack 0
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer f1 b1 
xfer f2 b2 
xfer f3 b3 
xfer f4 b4 
xfer f5 b5 
xfer f6 b6 
xfer f7 b7 
xfer f8 b8 
xfer f9 b9 
xfer f10 b10 
xfer f11 b11 
xfer f12 b12 
xfer f13 b13 
xfer f14 b14 
xfer f15 b15 
xfer f16 b16 
xfer f17 b17 
xfer f18 b18 
xfer f19 b19 
xfer f20 b20 
xfer f21 b21 
xfer f22 b22 
xfer f23 b23 
xfer f24 b24 
xfer f25 b25 
xfer f26 b26 
xfer f27 b27 
xfer f28 b28 
xfer f29 b29 
xfer f30 b30 
xfer f31 b31 
xfer f32 b32 
xfer f33 b33 
xfer f34 b34 
xfer f35 b35 
xfer f36 b36 
xfer f37 b37 
xfer f38 b38 
xfer f39 b39 
xfer f40 b40 
xfer f41 b41 
xfer f42 b42 
xfer f43 b43 
xfer f44 b44 
xfer f45 b45 
xfer f46 b46 
xfer f47 b47 
xfer f48 b48 
rack -2
xfer f48 b50 
xfer f49 b51 
xfer f50 b52 
xfer f51 b53 
xfer f52 b54 
xfer f53 b55 
xfer f54 b56 
xfer f55 b57 
xfer f56 b58 
xfer f57 b59 
xfer f58 b60 
xfer f59 b61 
xfer f60 b62 
xfer f61 b63 
xfer f62 b64 
rack 0
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer f1 b1 
xfer f2 b2 
xfer f3 b3 
xfer f4 b4 
xfer f5 b5 
xfer f6 b6 
xfer f7 b7 
xfer f8 b8 
xfer f9 b9 
xfer f10 b10 
xfer f11 b11 
xfer f12 b12 
xfer f13 b13 
xfer f14 b14 
xfer f15 b15 
xfer f16 b16 
xfer f17 b17 
xfer f18 b18 
xfer f19 b19 
xfer f20 b20 
xfer f21 b21 
xfer f22 b22 
xfer f23 b23 
xfer f24 b24 
xfer f25 b25 
xfer f26 b26 
xfer f27 b27 
xfer f28 b28 
xfer f29 b29 
xfer f30 b30 
xfer f31 b31 
xfer f32 b32 
xfer f33 b33 
xfer f34 b34 
xfer f35 b35 
xfer f36 b36 
xfer f37 b37 
xfer f38 b38 
xfer f39 b39 
xfer f40 b40 
xfer f41 b41 
xfer f42 b42 
xfer f43 b43 
xfer f44 b44 
xfer f45 b45 
xfer f46 b46 
xfer f47 b47 
xfer f48 b48 
xfer f49 b49 
xfer f50 b50 
xfer f51 b51 
xfer f52 b52 
xfer f53 b53 
xfer f54 b54 
xfer f55 b55 
xfer f56 b56 
xfer f57 b57 
xfer f58 b58 
xfer f59 b59 
xfer f60 b60 
xfer f61 b61 
xfer f62 b62 
xfer f63 b63 
xfer f64 b64 
rack -2
xfer f64 b66 
rack 0
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer f1 b1 
xfer f2 b2 
xfer f3 b3 
xfer f4 b4 
xfer f5 b5 
xfer f6 b6 
xfer f7 b7 
xfer f8 b8 
xfer f9 b9 
xfer f10 b10 
xfer f11 b11 
xfer f12 b12 
xfer f13 b13 
xfer f14 b14 
xfer f15 b15 
xfer f16 b16 
xfer f17 b17 
xfer f18 b18 
rack -2
xfer f18 b20 
xfer f19 b21 
xfer f20 b22 
xfer f21 b23 
xfer f22 b24 
xfer f23 b25 
xfer f24 b26 
xfer f25 b27 
xfer f26 b28 
xfer f27 b29 
xfer f28 b30 
xfer f29 b31 
xfer f30 b32 
xfer f31 b33 
xfer f32 b34 
xfer f33 b35 
xfer f34 b36 
xfer f35 b37 
xfer f36 b38 
xfer f37 b39 
xfer f38 b40 
xfer f39 b41 
xfer f40 b42 
xfer f41 b43 
xfer f42 b44 
xfer f43 b45 
xfer f44 b46 
xfer f45 b47 
xfer f46 b48 
xfer f47 b49 
xfer f48 b50 
xfer f49 b51 
xfer f50 b52 
xfer f51 b53 
xfer f52 b54 
xfer f53 b55 
xfer f54 b56 
xfer f55 b57 
xfer f56 b58 
xfer f57 b59 
xfer f58 b60 
xfer f59 b61 
xfer f60 b62 
xfer f61 b63 
xfer f62 b64 
xfer f63 b65 
xfer f64 b66 
xfer f65 b67 
xfer f66 b68 
rack 0
xfer b66 f66 
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer f1 b1 
xfer f2 b2 
xfer f3 b3 
xfer f4 b4 
xfer f5 b5 
xfer f6 b6 
xfer f7 b7 
xfer f8 b8 
xfer f9 b9 
xfer f10 b10 
xfer f11 b11 
xfer f12 b12 
xfer f13 b13 
xfer f14 b14 
xfer f15 b15 
xfer f16 b16 
xfer f17 b17 
xfer f18 b18 
xfer f19 b19 
xfer f20 b20 
xfer f21 b21 
xfer f22 b22 
xfer f23 b23 
xfer f24 b24 
xfer f25 b25 
xfer f26 b26 
xfer f27 b27 
xfer f28 b28 
xfer f29 b29 
xfer f30 b30 
xfer f31 b31 
xfer f32 b32 
xfer f33 b33 
xfer f34 b34 
xfer f35 b35 
xfer f36 b36 
rack -2
xfer f36 b38 
xfer f37 b39 
xfer f38 b40 
xfer f39 b41 
xfer f40 b42 
xfer f41 b43 
xfer f42 b44 
xfer f43 b45 
xfer f44 b46 
xfer f45 b47 
xfer f46 b48 
xfer f47 b49 
xfer f48 b50 
xfer f49 b51 
xfer f50 b52 
xfer f51 b53 
xfer f52 b54 
xfer f53 b55 
xfer f54 b56 
xfer f55 b57 
xfer f56 b58 
xfer f57 b59 
xfer f58 b60 
xfer f59 b61 
xfer f60 b62 
xfer f61 b63 
xfer f62 b64 
xfer f63 b65 
xfer f64 b66 
xfer f65 b67 
xfer f66 b68 
xfer f67 b69 
xfer f68 b70 
rack 0
xfer b68 f68 
xfer b66 f66 
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer b69 f69 
xfer f1 b1 
xfer f2 b2 
xfer f3 b3 
xfer f4 b4 
xfer f5 b5 
xfer f6 b6 
xfer f7 b7 
xfer f8 b8 
xfer f9 b9 
xfer f10 b10 
xfer f11 b11 
xfer f12 b12 
xfer f13 b13 
xfer f14 b14 
xfer f15 b15 
xfer f16 b16 
xfer f17 b17 
xfer f18 b18 
xfer f19 b19 
xfer f20 b20 
xfer f21 b21 
xfer f22 b22 
xfer f23 b23 
xfer f24 b24 
xfer f25 b25 
xfer f26 b26 
xfer f27 b27 
xfer f28 b28 
xfer f29 b29 
xfer f30 b30 
xfer f31 b31 
xfer f32 b32 
xfer f33 b33 
xfer f34 b34 
xfer f35 b35 
xfer f36 b36 
xfer f37 b37 
xfer f38 b38 
xfer f39 b39 
xfer f40 b40 
xfer f41 b41 
xfer f42 b42 
xfer f43 b43 
xfer f44 b44 
xfer f45 b45 
xfer f46 b46 
xfer f47 b47 
xfer f48 b48 
xfer f49 b49 
xfer f50 b50 
xfer f51 b51 
xfer f52 b52 
xfer f53 b53 
xfer f54 b54 
rack -2
xfer f54 b56 
xfer f55 b57 
xfer f56 b58 
xfer f57 b59 
xfer f58 b60 
xfer f59 b61 
xfer f60 b62 
xfer f61 b63 
xfer f62 b64 
xfer f63 b65 
xfer f64 b66 
xfer f65 b67 
xfer f66 b68 
xfer f67 b69 
xfer f68 b70 
xfer f69 b71 
xfer f70 b72 
rack 0
xfer b70 f70 
xfer b68 f68 
xfer b66 f66 
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer b69 f69 
xfer b71 f71 
xfer f1 b1 
xfer f2 b2 
xfer f3 b3 
xfer f4 b4 
xfer f5 b5 
xfer f6 b6 
xfer f7 b7 
xfer f8 b8 
xfer f9 b9 
xfer f10 b10 
xfer f11 b11 
xfer f12 b12 
xfer f13 b13 
xfer f14 b14 
xfer f15 b15 
xfer f16 b16 
xfer f17 b17 
xfer f18 b18 
xfer f19 b19 
xfer f20 b20 
xfer f21 b21 
xfer f22 b22 
xfer f23 b23 
xfer f24 b24 
xfer f25 b25 
xfer f26 b26 
xfer f27 b27 
xfer f28 b28 
xfer f29 b29 
xfer f30 b30 
xfer f31 b31 
xfer f32 b32 
xfer f33 b33 
xfer f34 b34 
xfer f35 b35 
xfer f36 b36 
xfer f37 b37 
xfer f38 b38 
xfer f39 b39 
xfer f40 b40 
xfer f41 b41 
xfer f42 b42 
xfer f43 b43 
xfer f44 b44 
xfer f45 b45 
xfer f46 b46 
xfer f47 b47 
xfer f48 b48 
xfer f49 b49 
xfer f50 b50 
xfer f51 b51 
xfer f52 b52 
xfer f53 b53 
xfer f54 b54 
xfer f55 b55 
xfer f56 b56 
xfer f57 b57 
xfer f58 b58 
xfer f59 b59 
xfer f60 b60 
xfer f61 b61 
xfer f62 b62 
xfer f63 b63 
xfer f64 b64 
xfer f65 b65 
xfer f66 b66 
xfer f67 b67 
xfer f68 b68 
xfer f69 b69 
xfer f70 b70 
xfer f71 b71 
xfer f72 b72 
rack -2
xfer f72 b74 
rack 0
xfer b72 f72 
xfer b70 f70 
xfer b68 f68 
xfer b66 f66 
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer b69 f69 
xfer b71 f71 
xfer b73 f73 
xfer f1 b1 
xfer f2 b2 
xfer f3 b3 
xfer f4 b4 
xfer f5 b5 
xfer f6 b6 
xfer f7 b7 
xfer f8 b8 
xfer f9 b9 
xfer f10 b10 
xfer f11 b11 
xfer f12 b12 
xfer f13 b13 
xfer f14 b14 
xfer f15 b15 
xfer f16 b16 
xfer f17 b17 
xfer f18 b18 
xfer f19 b19 
xfer f20 b20 
rack -2
xfer f20 b22 
xfer f21 b23 
xfer f22 b24 
xfer f23 b25 
xfer f24 b26 
xfer f25 b27 
xfer f26 b28 
xfer f27 b29 
xfer f28 b30 
xfer f29 b31 
xfer f30 b32 
xfer f31 b33 
xfer f32 b34 
xfer f33 b35 
xfer f34 b36 
xfer f35 b37 
xfer f36 b38 
xfer f37 b39 
xfer f38 b40 
xfer f39 b41 
xfer f40 b42 
xfer f41 b43 
xfer f42 b44 
xfer f43 b45 
xfer f44 b46 
xfer f45 b47 
xfer f46 b48 
xfer f47 b49 
xfer f48 b50 
xfer f49 b51 
xfer f50 b52 
xfer f51 b53 
xfer f52 b54 
xfer f53 b55 
xfer f54 b56 
xfer f55 b57 
xfer f56 b58 
xfer f57 b59 
xfer f58 b60 
xfer f59 b61 
xfer f60 b62 
xfer f61 b63 
xfer f62 b64 
xfer f63 b65 
xfer f64 b66 
xfer f65 b67 
xfer f66 b68 
xfer f67 b69 
xfer f68 b70 
xfer f69 b71 
xfer f70 b72 
xfer f71 b73 
xfer f72 b74 
xfer f73 b75 
xfer f74 b76 
rack 0
xfer b74 f74 
xfer b72 f72 
xfer b70 f70 
xfer b68 f68 
xfer b66 f66 
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer b69 f69 
xfer b71 f71 
xfer b73 f73 
xfer b75 f75 
xfer f1 b1 
xfer f2 b2 
xfer f3 b3 
xfer f4 b4 
xfer f5 b5 
xfer f6 b6 
xfer f7 b7 
xfer f8 b8 
xfer f9 b9 
xfer f10 b10 
xfer f11 b11 
xfer f12 b12 
xfer f13 b13 
xfer f14 b14 
xfer f15 b15 
xfer f16 b16 
xfer f17 b17 
xfer f18 b18 
xfer f19 b19 
xfer f20 b20 
xfer f21 b21 
xfer f22 b22 
xfer f23 b23 
xfer f24 b24 
xfer f25 b25 
xfer f26 b26 
xfer f27 b27 
xfer f28 b28 
xfer f29 b29 
xfer f30 b30 
xfer f31 b31 
xfer f32 b32 
xfer f33 b33 
xfer f34 b34 
xfer f35 b35 
xfer f36 b36 
xfer f37 b37 
xfer f38 b38 
xfer f39 b39 
xfer f40 b40 
rack -2
xfer f40 b42 
xfer f41 b43 
xfer f42 b44 
xfer f43 b45 
xfer f44 b46 
xfer f45 b47 
xfer f46 b48 
xfer f47 b49 
xfer f48 b50 
xfer f49 b51 
xfer f50 b52 
xfer f51 b53 
xfer f52 b54 
xfer f53 b55 
xfer f54 b56 
xfer f55 b57 
xfer f56 b58 
xfer f57 b59 
xfer f58 b60 
xfer f59 b61 
xfer f60 b62 
xfer f61 b63 
xfer f62 b64 
xfer f63 b65 
xfer f64 b66 
xfer f65 b67 
xfer f66 b68 
xfer f67 b69 
xfer f68 b70 
xfer f69 b71 
xfer f70 b72 
xfer f71 b73 
xfer f72 b74 
xfer f73 b75 
xfer f74 b76 
xfer f75 b77 
xfer f76 b78 
rack 0
xfer b76 f76 
xfer b74 f74 
xfer b72 f72 
xfer b70 f70 
xfer b68 f68 
xfer b66 f66 
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer b69 f69 
xfer b71 f71 
xfer b73 f73 
xfer b75 f75 
xfer b77 f77 
xfer f1 b1 
xfer f2 b2 
xfer f3 b3 
xfer f4 b4 
xfer f5 b5 
xfer f6 b6 
xfer f7 b7 
xfer f8 b8 
xfer f9 b9 
xfer f10 b10 
xfer f11 b11 
xfer f12 b12 
xfer f13 b13 
xfer f14 b14 
xfer f15 b15 
xfer f16 b16 
xfer f17 b17 
xfer f18 b18 
xfer f19 b19 
xfer f20 b20 
xfer f21 b21 
xfer f22 b22 
xfer f23 b23 
xfer f24 b24 
xfer f25 b25 
xfer f26 b26 
xfer f27 b27 
xfer f28 b28 
xfer f29 b29 
xfer f30 b30 
xfer f31 b31 
xfer f32 b32 
xfer f33 b33 
xfer f34 b34 
xfer f35 b35 
xfer f36 b36 
xfer f37 b37 
xfer f38 b38 
xfer f39 b39 
xfer f40 b40 
xfer f41 b41 
xfer f42 b42 
xfer f43 b43 
xfer f44 b44 
xfer f45 b45 
xfer f46 b46 
xfer f47 b47 
xfer f48 b48 
xfer f49 b49 
xfer f50 b50 
xfer f51 b51 
xfer f52 b52 
xfer f53 b53 
xfer f54 b54 
xfer f55 b55 
xfer f56 b56 
xfer f57 b57 
xfer f58 b58 
xfer f59 b59 
xfer f60 b60 
rack -2
xfer f60 b62 
xfer f61 b63 
xfer f62 b64 
xfer f63 b65 
xfer f64 b66 
xfer f65 b67 
xfer f66 b68 
xfer f67 b69 
xfer f68 b70 
xfer f69 b71 
xfer f70 b72 
xfer f71 b73 
xfer f72 b74 
xfer f73 b75 
xfer f74 b76 
xfer f75 b77 
xfer f76 b78 
xfer f77 b79 
xfer f78 b80 
rack 0
xfer b78 f78 
xfer b76 f76 
xfer b74 f74 
xfer b72 f72 
xfer b70 f70 
xfer b68 f68 
xfer b66 f66 
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer b69 f69 
xfer b71 f71 
xfer b73 f73 
xfer b75 f75 
xfer b77 f77 
xfer b79 f79 
xfer f1 b1 
xfer f2 b2 
xfer f3 b3 
xfer f4 b4 
xfer f5 b5 
xfer f6 b6 
xfer f7 b7 
xfer f8 b8 
xfer f9 b9 
xfer f10 b10 
xfer f11 b11 
xfer f12 b12 
xfer f13 b13 
xfer f14 b14 
xfer f15 b15 
xfer f16 b16 
xfer f17 b17 
xfer f18 b18 
xfer f19 b19 
xfer f20 b20 
xfer f21 b21 
xfer f22 b22 
xfer f23 b23 
xfer f24 b24 
xfer f25 b25 
xfer f26 b26 
xfer f27 b27 
xfer f28 b28 
xfer f29 b29 
xfer f30 b30 
xfer f31 b31 
xfer f32 b32 
xfer f33 b33 
xfer f34 b34 
xfer f35 b35 
xfer f36 b36 
xfer f37 b37 
xfer f38 b38 
xfer f39 b39 
xfer f40 b40 
xfer f41 b41 
xfer f42 b42 
xfer f43 b43 
xfer f44 b44 
xfer f45 b45 
xfer f46 b46 
xfer f47 b47 
xfer f48 b48 
xfer f49 b49 
xfer f50 b50 
xfer f51 b51 
xfer f52 b52 
xfer f53 b53 
xfer f54 b54 
xfer f55 b55 
xfer f56 b56 
xfer f57 b57 
xfer f58 b58 
xfer f59 b59 
xfer f60 b60 
xfer f61 b61 
xfer f62 b62 
xfer f63 b63 
xfer f64 b64 
xfer f65 b65 
xfer f66 b66 
xfer f67 b67 
xfer f68 b68 
xfer f69 b69 
xfer f70 b70 
xfer f71 b71 
xfer f72 b72 
xfer f73 b73 
xfer f74 b74 
xfer f75 b75 
xfer f76 b76 
xfer f77 b77 
xfer f78 b78 
xfer f79 b79 
xfer f80 b80 
rack -2
xfer f80 b82 
rack 0
xfer b80 f80 
xfer b78 f78 
xfer b76 f76 
xfer b74 f74 
xfer b72 f72 
xfer b70 f70 
xfer b68 f68 
xfer b66 f66 
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
knit - f80 3 
knit - f78 3 
knit - f76 3 
knit - f74 3 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
knit + b73 3 
knit + b75 3 
knit + b77 3 
knit + b79 3 
knit - f80 3 
knit - f78 3 
knit - f76 3 
knit - f74 3 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
knit + b73 3 
knit + b75 3 
knit + b77 3 
knit + b79 3 
knit - f80 3 
knit - f78 3 
knit - f76 3 
knit - f74 3 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
knit + b73 3 
knit + b75 3 
knit + b77 3 
knit + b79 3 
knit - f80 3 
knit - f78 3 
knit - f76 3 
knit - f74 3 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
knit + b73 3 
knit + b75 3 
knit + b77 3 
knit + b79 3 
knit - f80 3 
knit - f78 3 
knit - f76 3 
knit - f74 3 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
knit + b73 3 
knit + b75 3 
knit + b77 3 
knit + b79 3 
knit - f80 3 
knit - f78 3 
knit - f76 3 
knit - f74 3 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
knit + b73 3 
knit + b75 3 
knit + b77 3 
knit + b79 3 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer b69 f69 
xfer b71 f71 
xfer b73 f73 
xfer b75 f75 
xfer b77 f77 
xfer b79 f79 
xfer b81 f81 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
rack 2
xfer f19 b17 
xfer f21 b19 
xfer f23 b21 
xfer f25 b23 
xfer f27 b25 
xfer f29 b27 
xfer f31 b29 
xfer f33 b31 
xfer f35 b33 
xfer f37 b35 
xfer f39 b37 
xfer f41 b39 
xfer f43 b41 
xfer f45 b43 
xfer f47 b45 
xfer f49 b47 
xfer f51 b49 
xfer f53 b51 
xfer f55 b53 
xfer f57 b55 
xfer f59 b57 
xfer f61 b59 
xfer f63 b61 
xfer f65 b63 
xfer f67 b65 
xfer f69 b67 
xfer f71 b69 
xfer f73 b71 
xfer f75 b73 
xfer f77 b75 
xfer f79 b77 
xfer f81 b79 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
rack 2
xfer f18 b16 
xfer f20 b18 
xfer f22 b20 
xfer f24 b22 
xfer f26 b24 
xfer f28 b26 
xfer f30 b28 
xfer f32 b30 
xfer f34 b32 
xfer f36 b34 
xfer f38 b36 
xfer f40 b38 
xfer f42 b40 
xfer f44 b42 
xfer f46 b44 
xfer f48 b46 
xfer f50 b48 
xfer f52 b50 
xfer f54 b52 
xfer f56 b54 
xfer f58 b56 
xfer f60 b58 
xfer f62 b60 
xfer f64 b62 
xfer f66 b64 
xfer f68 b66 
xfer f70 b68 
xfer f72 b70 
xfer f74 b72 
xfer f76 b74 
xfer f78 b76 
xfer f80 b78 
xfer f82 b80 
rack 0
xfer b78 f78 
xfer b76 f76 
xfer b74 f74 
xfer b72 f72 
xfer b70 f70 
xfer b68 f68 
xfer b66 f66 
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer b69 f69 
xfer b71 f71 
xfer b73 f73 
xfer b75 f75 
xfer b77 f77 
xfer b79 f79 
xfer b81 f81 
xfer b83 f83 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
xfer f21 b21 
xfer f23 b23 
xfer f25 b25 
xfer f27 b27 
xfer f29 b29 
xfer f31 b31 
xfer f33 b33 
xfer f35 b35 
rack 2
xfer f37 b35 
xfer f39 b37 
xfer f41 b39 
xfer f43 b41 
xfer f45 b43 
xfer f47 b45 
xfer f49 b47 
xfer f51 b49 
xfer f53 b51 
xfer f55 b53 
xfer f57 b55 
xfer f59 b57 
xfer f61 b59 
xfer f63 b61 
xfer f65 b63 
xfer f67 b65 
xfer f69 b67 
xfer f71 b69 
xfer f73 b71 
xfer f75 b73 
xfer f77 b75 
xfer f79 b77 
xfer f81 b79 
xfer f83 b81 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
xfer f22 b22 
xfer f24 b24 
xfer f26 b26 
xfer f28 b28 
xfer f30 b30 
xfer f32 b32 
xfer f34 b34 
xfer f36 b36 
rack 2
xfer f36 b34 
xfer f38 b36 
xfer f40 b38 
xfer f42 b40 
xfer f44 b42 
xfer f46 b44 
xfer f48 b46 
xfer f50 b48 
xfer f52 b50 
xfer f54 b52 
xfer f56 b54 
xfer f58 b56 
xfer f60 b58 
xfer f62 b60 
xfer f64 b62 
xfer f66 b64 
xfer f68 b66 
xfer f70 b68 
xfer f72 b70 
xfer f74 b72 
xfer f76 b74 
xfer f78 b76 
xfer f80 b78 
xfer f82 b80 
xfer f84 b82 
rack 0
xfer b76 f76 
xfer b74 f74 
xfer b72 f72 
xfer b70 f70 
xfer b68 f68 
xfer b66 f66 
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer b69 f69 
xfer b71 f71 
xfer b73 f73 
xfer b75 f75 
xfer b77 f77 
xfer b79 f79 
xfer b81 f81 
xfer b83 f83 
xfer b85 f85 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
xfer f21 b21 
xfer f23 b23 
xfer f25 b25 
xfer f27 b27 
xfer f29 b29 
xfer f31 b31 
xfer f33 b33 
xfer f35 b35 
xfer f37 b37 
xfer f39 b39 
xfer f41 b41 
xfer f43 b43 
xfer f45 b45 
xfer f47 b47 
xfer f49 b49 
xfer f51 b51 
xfer f53 b53 
rack 2
xfer f55 b53 
xfer f57 b55 
xfer f59 b57 
xfer f61 b59 
xfer f63 b61 
xfer f65 b63 
xfer f67 b65 
xfer f69 b67 
xfer f71 b69 
xfer f73 b71 
xfer f75 b73 
xfer f77 b75 
xfer f79 b77 
xfer f81 b79 
xfer f83 b81 
xfer f85 b83 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
xfer f22 b22 
xfer f24 b24 
xfer f26 b26 
xfer f28 b28 
xfer f30 b30 
xfer f32 b32 
xfer f34 b34 
xfer f36 b36 
xfer f38 b38 
xfer f40 b40 
xfer f42 b42 
xfer f44 b44 
xfer f46 b46 
xfer f48 b48 
xfer f50 b50 
xfer f52 b52 
xfer f54 b54 
rack 2
xfer f54 b52 
xfer f56 b54 
xfer f58 b56 
xfer f60 b58 
xfer f62 b60 
xfer f64 b62 
xfer f66 b64 
xfer f68 b66 
xfer f70 b68 
xfer f72 b70 
xfer f74 b72 
xfer f76 b74 
xfer f78 b76 
xfer f80 b78 
xfer f82 b80 
xfer f84 b82 
xfer f86 b84 
rack 0
xfer b74 f74 
xfer b72 f72 
xfer b70 f70 
xfer b68 f68 
xfer b66 f66 
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer b69 f69 
xfer b71 f71 
xfer b73 f73 
xfer b75 f75 
xfer b77 f77 
xfer b79 f79 
xfer b81 f81 
xfer b83 f83 
xfer b85 f85 
xfer b87 f87 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
xfer f21 b21 
xfer f23 b23 
xfer f25 b25 
xfer f27 b27 
xfer f29 b29 
xfer f31 b31 
xfer f33 b33 
xfer f35 b35 
xfer f37 b37 
xfer f39 b39 
xfer f41 b41 
xfer f43 b43 
xfer f45 b45 
xfer f47 b47 
xfer f49 b49 
xfer f51 b51 
xfer f53 b53 
xfer f55 b55 
xfer f57 b57 
xfer f59 b59 
xfer f61 b61 
xfer f63 b63 
xfer f65 b65 
xfer f67 b67 
xfer f69 b69 
xfer f71 b71 
rack 2
xfer f73 b71 
xfer f75 b73 
xfer f77 b75 
xfer f79 b77 
xfer f81 b79 
xfer f83 b81 
xfer f85 b83 
xfer f87 b85 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
xfer f22 b22 
xfer f24 b24 
xfer f26 b26 
xfer f28 b28 
xfer f30 b30 
xfer f32 b32 
xfer f34 b34 
xfer f36 b36 
xfer f38 b38 
xfer f40 b40 
xfer f42 b42 
xfer f44 b44 
xfer f46 b46 
xfer f48 b48 
xfer f50 b50 
xfer f52 b52 
xfer f54 b54 
xfer f56 b56 
xfer f58 b58 
xfer f60 b60 
xfer f62 b62 
xfer f64 b64 
xfer f66 b66 
xfer f68 b68 
xfer f70 b70 
xfer f72 b72 
rack 2
xfer f72 b70 
xfer f74 b72 
xfer f76 b74 
xfer f78 b76 
xfer f80 b78 
xfer f82 b80 
xfer f84 b82 
xfer f86 b84 
xfer f88 b86 
rack 0
xfer b72 f72 
xfer b70 f70 
xfer b68 f68 
xfer b66 f66 
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
knit - f72 3 
knit - f70 3 
knit - f68 3 
knit - f66 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit + b65 3 
knit + b67 3 
knit + b69 3 
knit + b71 3 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer b69 f69 
xfer b71 f71 
xfer b73 f73 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
rack 2
xfer f17 b15 
xfer f19 b17 
xfer f21 b19 
xfer f23 b21 
xfer f25 b23 
xfer f27 b25 
xfer f29 b27 
xfer f31 b29 
xfer f33 b31 
xfer f35 b33 
xfer f37 b35 
xfer f39 b37 
xfer f41 b39 
xfer f43 b41 
xfer f45 b43 
xfer f47 b45 
xfer f49 b47 
xfer f51 b49 
xfer f53 b51 
xfer f55 b53 
xfer f57 b55 
xfer f59 b57 
xfer f61 b59 
xfer f63 b61 
xfer f65 b63 
xfer f67 b65 
xfer f69 b67 
xfer f71 b69 
xfer f73 b71 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
rack 2
xfer f16 b14 
xfer f18 b16 
xfer f20 b18 
xfer f22 b20 
xfer f24 b22 
xfer f26 b24 
xfer f28 b26 
xfer f30 b28 
xfer f32 b30 
xfer f34 b32 
xfer f36 b34 
xfer f38 b36 
xfer f40 b38 
xfer f42 b40 
xfer f44 b42 
xfer f46 b44 
xfer f48 b46 
xfer f50 b48 
xfer f52 b50 
xfer f54 b52 
xfer f56 b54 
xfer f58 b56 
xfer f60 b58 
xfer f62 b60 
xfer f64 b62 
xfer f66 b64 
xfer f68 b66 
xfer f70 b68 
xfer f72 b70 
xfer f74 b72 
rack 0
xfer b70 f70 
xfer b68 f68 
xfer b66 f66 
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer b69 f69 
xfer b71 f71 
xfer b73 f73 
xfer b75 f75 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
xfer f21 b21 
xfer f23 b23 
xfer f25 b25 
xfer f27 b27 
xfer f29 b29 
xfer f31 b31 
rack 2
xfer f33 b31 
xfer f35 b33 
xfer f37 b35 
xfer f39 b37 
xfer f41 b39 
xfer f43 b41 
xfer f45 b43 
xfer f47 b45 
xfer f49 b47 
xfer f51 b49 
xfer f53 b51 
xfer f55 b53 
xfer f57 b55 
xfer f59 b57 
xfer f61 b59 
xfer f63 b61 
xfer f65 b63 
xfer f67 b65 
xfer f69 b67 
xfer f71 b69 
xfer f73 b71 
xfer f75 b73 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
xfer f22 b22 
xfer f24 b24 
xfer f26 b26 
xfer f28 b28 
xfer f30 b30 
xfer f32 b32 
rack 2
xfer f32 b30 
xfer f34 b32 
xfer f36 b34 
xfer f38 b36 
xfer f40 b38 
xfer f42 b40 
xfer f44 b42 
xfer f46 b44 
xfer f48 b46 
xfer f50 b48 
xfer f52 b50 
xfer f54 b52 
xfer f56 b54 
xfer f58 b56 
xfer f60 b58 
xfer f62 b60 
xfer f64 b62 
xfer f66 b64 
xfer f68 b66 
xfer f70 b68 
xfer f72 b70 
xfer f74 b72 
xfer f76 b74 
rack 0
xfer b68 f68 
xfer b66 f66 
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer b69 f69 
xfer b71 f71 
xfer b73 f73 
xfer b75 f75 
xfer b77 f77 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
xfer f21 b21 
xfer f23 b23 
xfer f25 b25 
xfer f27 b27 
xfer f29 b29 
xfer f31 b31 
xfer f33 b33 
xfer f35 b35 
xfer f37 b37 
xfer f39 b39 
xfer f41 b41 
xfer f43 b43 
xfer f45 b45 
xfer f47 b47 
rack 2
xfer f49 b47 
xfer f51 b49 
xfer f53 b51 
xfer f55 b53 
xfer f57 b55 
xfer f59 b57 
xfer f61 b59 
xfer f63 b61 
xfer f65 b63 
xfer f67 b65 
xfer f69 b67 
xfer f71 b69 
xfer f73 b71 
xfer f75 b73 
xfer f77 b75 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
xfer f22 b22 
xfer f24 b24 
xfer f26 b26 
xfer f28 b28 
xfer f30 b30 
xfer f32 b32 
xfer f34 b34 
xfer f36 b36 
xfer f38 b38 
xfer f40 b40 
xfer f42 b42 
xfer f44 b44 
xfer f46 b46 
xfer f48 b48 
rack 2
xfer f48 b46 
xfer f50 b48 
xfer f52 b50 
xfer f54 b52 
xfer f56 b54 
xfer f58 b56 
xfer f60 b58 
xfer f62 b60 
xfer f64 b62 
xfer f66 b64 
xfer f68 b66 
xfer f70 b68 
xfer f72 b70 
xfer f74 b72 
xfer f76 b74 
xfer f78 b76 
rack 0
xfer b66 f66 
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer b69 f69 
xfer b71 f71 
xfer b73 f73 
xfer b75 f75 
xfer b77 f77 
xfer b79 f79 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
xfer f21 b21 
xfer f23 b23 
xfer f25 b25 
xfer f27 b27 
xfer f29 b29 
xfer f31 b31 
xfer f33 b33 
xfer f35 b35 
xfer f37 b37 
xfer f39 b39 
xfer f41 b41 
xfer f43 b43 
xfer f45 b45 
xfer f47 b47 
xfer f49 b49 
xfer f51 b51 
xfer f53 b53 
xfer f55 b55 
xfer f57 b57 
xfer f59 b59 
xfer f61 b61 
xfer f63 b63 
rack 2
xfer f65 b63 
xfer f67 b65 
xfer f69 b67 
xfer f71 b69 
xfer f73 b71 
xfer f75 b73 
xfer f77 b75 
xfer f79 b77 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
xfer f22 b22 
xfer f24 b24 
xfer f26 b26 
xfer f28 b28 
xfer f30 b30 
xfer f32 b32 
xfer f34 b34 
xfer f36 b36 
xfer f38 b38 
xfer f40 b40 
xfer f42 b42 
xfer f44 b44 
xfer f46 b46 
xfer f48 b48 
xfer f50 b50 
xfer f52 b52 
xfer f54 b54 
xfer f56 b56 
xfer f58 b58 
xfer f60 b60 
xfer f62 b62 
xfer f64 b64 
rack 2
xfer f64 b62 
xfer f66 b64 
xfer f68 b66 
xfer f70 b68 
xfer f72 b70 
xfer f74 b72 
xfer f76 b74 
xfer f78 b76 
xfer f80 b78 
rack 0
xfer b64 f64 
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
knit - f64 3 
knit - f62 3 
knit - f60 3 
knit - f58 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit + b57 3 
knit + b59 3 
knit + b61 3 
knit + b63 3 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
rack 2
xfer f15 b13 
xfer f17 b15 
xfer f19 b17 
xfer f21 b19 
xfer f23 b21 
xfer f25 b23 
xfer f27 b25 
xfer f29 b27 
xfer f31 b29 
xfer f33 b31 
xfer f35 b33 
xfer f37 b35 
xfer f39 b37 
xfer f41 b39 
xfer f43 b41 
xfer f45 b43 
xfer f47 b45 
xfer f49 b47 
xfer f51 b49 
xfer f53 b51 
xfer f55 b53 
xfer f57 b55 
xfer f59 b57 
xfer f61 b59 
xfer f63 b61 
xfer f65 b63 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
rack 2
xfer f14 b12 
xfer f16 b14 
xfer f18 b16 
xfer f20 b18 
xfer f22 b20 
xfer f24 b22 
xfer f26 b24 
xfer f28 b26 
xfer f30 b28 
xfer f32 b30 
xfer f34 b32 
xfer f36 b34 
xfer f38 b36 
xfer f40 b38 
xfer f42 b40 
xfer f44 b42 
xfer f46 b44 
xfer f48 b46 
xfer f50 b48 
xfer f52 b50 
xfer f54 b52 
xfer f56 b54 
xfer f58 b56 
xfer f60 b58 
xfer f62 b60 
xfer f64 b62 
xfer f66 b64 
rack 0
xfer b62 f62 
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
xfer f21 b21 
xfer f23 b23 
xfer f25 b25 
xfer f27 b27 
rack 2
xfer f29 b27 
xfer f31 b29 
xfer f33 b31 
xfer f35 b33 
xfer f37 b35 
xfer f39 b37 
xfer f41 b39 
xfer f43 b41 
xfer f45 b43 
xfer f47 b45 
xfer f49 b47 
xfer f51 b49 
xfer f53 b51 
xfer f55 b53 
xfer f57 b55 
xfer f59 b57 
xfer f61 b59 
xfer f63 b61 
xfer f65 b63 
xfer f67 b65 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
xfer f22 b22 
xfer f24 b24 
xfer f26 b26 
xfer f28 b28 
rack 2
xfer f28 b26 
xfer f30 b28 
xfer f32 b30 
xfer f34 b32 
xfer f36 b34 
xfer f38 b36 
xfer f40 b38 
xfer f42 b40 
xfer f44 b42 
xfer f46 b44 
xfer f48 b46 
xfer f50 b48 
xfer f52 b50 
xfer f54 b52 
xfer f56 b54 
xfer f58 b56 
xfer f60 b58 
xfer f62 b60 
xfer f64 b62 
xfer f66 b64 
xfer f68 b66 
rack 0
xfer b60 f60 
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer b69 f69 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
xfer f21 b21 
xfer f23 b23 
xfer f25 b25 
xfer f27 b27 
xfer f29 b29 
xfer f31 b31 
xfer f33 b33 
xfer f35 b35 
xfer f37 b37 
xfer f39 b39 
xfer f41 b41 
rack 2
xfer f43 b41 
xfer f45 b43 
xfer f47 b45 
xfer f49 b47 
xfer f51 b49 
xfer f53 b51 
xfer f55 b53 
xfer f57 b55 
xfer f59 b57 
xfer f61 b59 
xfer f63 b61 
xfer f65 b63 
xfer f67 b65 
xfer f69 b67 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
xfer f22 b22 
xfer f24 b24 
xfer f26 b26 
xfer f28 b28 
xfer f30 b30 
xfer f32 b32 
xfer f34 b34 
xfer f36 b36 
xfer f38 b38 
xfer f40 b40 
xfer f42 b42 
rack 2
xfer f42 b40 
xfer f44 b42 
xfer f46 b44 
xfer f48 b46 
xfer f50 b48 
xfer f52 b50 
xfer f54 b52 
xfer f56 b54 
xfer f58 b56 
xfer f60 b58 
xfer f62 b60 
xfer f64 b62 
xfer f66 b64 
xfer f68 b66 
xfer f70 b68 
rack 0
xfer b58 f58 
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer b65 f65 
xfer b67 f67 
xfer b69 f69 
xfer b71 f71 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
xfer f21 b21 
xfer f23 b23 
xfer f25 b25 
xfer f27 b27 
xfer f29 b29 
xfer f31 b31 
xfer f33 b33 
xfer f35 b35 
xfer f37 b37 
xfer f39 b39 
xfer f41 b41 
xfer f43 b43 
xfer f45 b45 
xfer f47 b47 
xfer f49 b49 
xfer f51 b51 
xfer f53 b53 
xfer f55 b55 
rack 2
xfer f57 b55 
xfer f59 b57 
xfer f61 b59 
xfer f63 b61 
xfer f65 b63 
xfer f67 b65 
xfer f69 b67 
xfer f71 b69 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
xfer f22 b22 
xfer f24 b24 
xfer f26 b26 
xfer f28 b28 
xfer f30 b30 
xfer f32 b32 
xfer f34 b34 
xfer f36 b36 
xfer f38 b38 
xfer f40 b40 
xfer f42 b42 
xfer f44 b44 
xfer f46 b46 
xfer f48 b48 
xfer f50 b50 
xfer f52 b52 
xfer f54 b54 
xfer f56 b56 
rack 2
xfer f56 b54 
xfer f58 b56 
xfer f60 b58 
xfer f62 b60 
xfer f64 b62 
xfer f66 b64 
xfer f68 b66 
xfer f70 b68 
xfer f72 b70 
rack 0
xfer b56 f56 
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
knit - f56 3 
knit - f54 3 
knit - f52 3 
knit - f50 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit + b49 3 
knit + b51 3 
knit + b53 3 
knit + b55 3 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
rack 2
xfer f13 b11 
xfer f15 b13 
xfer f17 b15 
xfer f19 b17 
xfer f21 b19 
xfer f23 b21 
xfer f25 b23 
xfer f27 b25 
xfer f29 b27 
xfer f31 b29 
xfer f33 b31 
xfer f35 b33 
xfer f37 b35 
xfer f39 b37 
xfer f41 b39 
xfer f43 b41 
xfer f45 b43 
xfer f47 b45 
xfer f49 b47 
xfer f51 b49 
xfer f53 b51 
xfer f55 b53 
xfer f57 b55 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
rack 2
xfer f12 b10 
xfer f14 b12 
xfer f16 b14 
xfer f18 b16 
xfer f20 b18 
xfer f22 b20 
xfer f24 b22 
xfer f26 b24 
xfer f28 b26 
xfer f30 b28 
xfer f32 b30 
xfer f34 b32 
xfer f36 b34 
xfer f38 b36 
xfer f40 b38 
xfer f42 b40 
xfer f44 b42 
xfer f46 b44 
xfer f48 b46 
xfer f50 b48 
xfer f52 b50 
xfer f54 b52 
xfer f56 b54 
xfer f58 b56 
rack 0
xfer b54 f54 
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
xfer f21 b21 
xfer f23 b23 
rack 2
xfer f25 b23 
xfer f27 b25 
xfer f29 b27 
xfer f31 b29 
xfer f33 b31 
xfer f35 b33 
xfer f37 b35 
xfer f39 b37 
xfer f41 b39 
xfer f43 b41 
xfer f45 b43 
xfer f47 b45 
xfer f49 b47 
xfer f51 b49 
xfer f53 b51 
xfer f55 b53 
xfer f57 b55 
xfer f59 b57 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
xfer f22 b22 
xfer f24 b24 
rack 2
xfer f24 b22 
xfer f26 b24 
xfer f28 b26 
xfer f30 b28 
xfer f32 b30 
xfer f34 b32 
xfer f36 b34 
xfer f38 b36 
xfer f40 b38 
xfer f42 b40 
xfer f44 b42 
xfer f46 b44 
xfer f48 b46 
xfer f50 b48 
xfer f52 b50 
xfer f54 b52 
xfer f56 b54 
xfer f58 b56 
xfer f60 b58 
rack 0
xfer b52 f52 
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
xfer f21 b21 
xfer f23 b23 
xfer f25 b25 
xfer f27 b27 
xfer f29 b29 
xfer f31 b31 
xfer f33 b33 
xfer f35 b35 
rack 2
xfer f37 b35 
xfer f39 b37 
xfer f41 b39 
xfer f43 b41 
xfer f45 b43 
xfer f47 b45 
xfer f49 b47 
xfer f51 b49 
xfer f53 b51 
xfer f55 b53 
xfer f57 b55 
xfer f59 b57 
xfer f61 b59 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
xfer f22 b22 
xfer f24 b24 
xfer f26 b26 
xfer f28 b28 
xfer f30 b30 
xfer f32 b32 
xfer f34 b34 
xfer f36 b36 
rack 2
xfer f36 b34 
xfer f38 b36 
xfer f40 b38 
xfer f42 b40 
xfer f44 b42 
xfer f46 b44 
xfer f48 b46 
xfer f50 b48 
xfer f52 b50 
xfer f54 b52 
xfer f56 b54 
xfer f58 b56 
xfer f60 b58 
xfer f62 b60 
rack 0
xfer b50 f50 
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer b57 f57 
xfer b59 f59 
xfer b61 f61 
xfer b63 f63 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
xfer f21 b21 
xfer f23 b23 
xfer f25 b25 
xfer f27 b27 
xfer f29 b29 
xfer f31 b31 
xfer f33 b33 
xfer f35 b35 
xfer f37 b37 
xfer f39 b39 
xfer f41 b41 
xfer f43 b43 
xfer f45 b45 
xfer f47 b47 
rack 2
xfer f49 b47 
xfer f51 b49 
xfer f53 b51 
xfer f55 b53 
xfer f57 b55 
xfer f59 b57 
xfer f61 b59 
xfer f63 b61 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
xfer f22 b22 
xfer f24 b24 
xfer f26 b26 
xfer f28 b28 
xfer f30 b30 
xfer f32 b32 
xfer f34 b34 
xfer f36 b36 
xfer f38 b38 
xfer f40 b40 
xfer f42 b42 
xfer f44 b44 
xfer f46 b46 
xfer f48 b48 
rack 2
xfer f48 b46 
xfer f50 b48 
xfer f52 b50 
xfer f54 b52 
xfer f56 b54 
xfer f58 b56 
xfer f60 b58 
xfer f62 b60 
xfer f64 b62 
rack 0
xfer b48 f48 
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
knit - f48 3 
knit - f46 3 
knit - f44 3 
knit - f42 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit + b41 3 
knit + b43 3 
knit + b45 3 
knit + b47 3 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
rack 2
xfer f11 b9 
xfer f13 b11 
xfer f15 b13 
xfer f17 b15 
xfer f19 b17 
xfer f21 b19 
xfer f23 b21 
xfer f25 b23 
xfer f27 b25 
xfer f29 b27 
xfer f31 b29 
xfer f33 b31 
xfer f35 b33 
xfer f37 b35 
xfer f39 b37 
xfer f41 b39 
xfer f43 b41 
xfer f45 b43 
xfer f47 b45 
xfer f49 b47 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
rack 2
xfer f10 b8 
xfer f12 b10 
xfer f14 b12 
xfer f16 b14 
xfer f18 b16 
xfer f20 b18 
xfer f22 b20 
xfer f24 b22 
xfer f26 b24 
xfer f28 b26 
xfer f30 b28 
xfer f32 b30 
xfer f34 b32 
xfer f36 b34 
xfer f38 b36 
xfer f40 b38 
xfer f42 b40 
xfer f44 b42 
xfer f46 b44 
xfer f48 b46 
xfer f50 b48 
rack 0
xfer b46 f46 
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
rack 2
xfer f21 b19 
xfer f23 b21 
xfer f25 b23 
xfer f27 b25 
xfer f29 b27 
xfer f31 b29 
xfer f33 b31 
xfer f35 b33 
xfer f37 b35 
xfer f39 b37 
xfer f41 b39 
xfer f43 b41 
xfer f45 b43 
xfer f47 b45 
xfer f49 b47 
xfer f51 b49 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
rack 2
xfer f20 b18 
xfer f22 b20 
xfer f24 b22 
xfer f26 b24 
xfer f28 b26 
xfer f30 b28 
xfer f32 b30 
xfer f34 b32 
xfer f36 b34 
xfer f38 b36 
xfer f40 b38 
xfer f42 b40 
xfer f44 b42 
xfer f46 b44 
xfer f48 b46 
xfer f50 b48 
xfer f52 b50 
rack 0
xfer b44 f44 
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
xfer f21 b21 
xfer f23 b23 
xfer f25 b25 
xfer f27 b27 
xfer f29 b29 
rack 2
xfer f31 b29 
xfer f33 b31 
xfer f35 b33 
xfer f37 b35 
xfer f39 b37 
xfer f41 b39 
xfer f43 b41 
xfer f45 b43 
xfer f47 b45 
xfer f49 b47 
xfer f51 b49 
xfer f53 b51 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
xfer f22 b22 
xfer f24 b24 
xfer f26 b26 
xfer f28 b28 
xfer f30 b30 
rack 2
xfer f30 b28 
xfer f32 b30 
xfer f34 b32 
xfer f36 b34 
xfer f38 b36 
xfer f40 b38 
xfer f42 b40 
xfer f44 b42 
xfer f46 b44 
xfer f48 b46 
xfer f50 b48 
xfer f52 b50 
xfer f54 b52 
rack 0
xfer b42 f42 
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer b49 f49 
xfer b51 f51 
xfer b53 f53 
xfer b55 f55 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
xfer f21 b21 
xfer f23 b23 
xfer f25 b25 
xfer f27 b27 
xfer f29 b29 
xfer f31 b31 
xfer f33 b33 
xfer f35 b35 
xfer f37 b37 
xfer f39 b39 
rack 2
xfer f41 b39 
xfer f43 b41 
xfer f45 b43 
xfer f47 b45 
xfer f49 b47 
xfer f51 b49 
xfer f53 b51 
xfer f55 b53 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
xfer f22 b22 
xfer f24 b24 
xfer f26 b26 
xfer f28 b28 
xfer f30 b30 
xfer f32 b32 
xfer f34 b34 
xfer f36 b36 
xfer f38 b38 
xfer f40 b40 
rack 2
xfer f40 b38 
xfer f42 b40 
xfer f44 b42 
xfer f46 b44 
xfer f48 b46 
xfer f50 b48 
xfer f52 b50 
xfer f54 b52 
xfer f56 b54 
rack 0
xfer b40 f40 
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
knit - f40 3 
knit - f38 3 
knit - f36 3 
knit - f34 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit + b33 3 
knit + b35 3 
knit + b37 3 
knit + b39 3 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
rack 2
xfer f9 b7 
xfer f11 b9 
xfer f13 b11 
xfer f15 b13 
xfer f17 b15 
xfer f19 b17 
xfer f21 b19 
xfer f23 b21 
xfer f25 b23 
xfer f27 b25 
xfer f29 b27 
xfer f31 b29 
xfer f33 b31 
xfer f35 b33 
xfer f37 b35 
xfer f39 b37 
xfer f41 b39 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
rack 2
xfer f8 b6 
xfer f10 b8 
xfer f12 b10 
xfer f14 b12 
xfer f16 b14 
xfer f18 b16 
xfer f20 b18 
xfer f22 b20 
xfer f24 b22 
xfer f26 b24 
xfer f28 b26 
xfer f30 b28 
xfer f32 b30 
xfer f34 b32 
xfer f36 b34 
xfer f38 b36 
xfer f40 b38 
xfer f42 b40 
rack 0
xfer b38 f38 
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
rack 2
xfer f17 b15 
xfer f19 b17 
xfer f21 b19 
xfer f23 b21 
xfer f25 b23 
xfer f27 b25 
xfer f29 b27 
xfer f31 b29 
xfer f33 b31 
xfer f35 b33 
xfer f37 b35 
xfer f39 b37 
xfer f41 b39 
xfer f43 b41 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
rack 2
xfer f16 b14 
xfer f18 b16 
xfer f20 b18 
xfer f22 b20 
xfer f24 b22 
xfer f26 b24 
xfer f28 b26 
xfer f30 b28 
xfer f32 b30 
xfer f34 b32 
xfer f36 b34 
xfer f38 b36 
xfer f40 b38 
xfer f42 b40 
xfer f44 b42 
rack 0
xfer b36 f36 
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
xfer f21 b21 
xfer f23 b23 
rack 2
xfer f25 b23 
xfer f27 b25 
xfer f29 b27 
xfer f31 b29 
xfer f33 b31 
xfer f35 b33 
xfer f37 b35 
xfer f39 b37 
xfer f41 b39 
xfer f43 b41 
xfer f45 b43 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
xfer f22 b22 
xfer f24 b24 
rack 2
xfer f24 b22 
xfer f26 b24 
xfer f28 b26 
xfer f30 b28 
xfer f32 b30 
xfer f34 b32 
xfer f36 b34 
xfer f38 b36 
xfer f40 b38 
xfer f42 b40 
xfer f44 b42 
xfer f46 b44 
rack 0
xfer b34 f34 
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
xfer b1 f1 
xfer b3 f3 
xfer b5 f5 
xfer b7 f7 
xfer b9 f9 
xfer b11 f11 
xfer b13 f13 
xfer b15 f15 
xfer b17 f17 
xfer b19 f19 
xfer b21 f21 
xfer b23 f23 
xfer b25 f25 
xfer b27 f27 
xfer b29 f29 
xfer b31 f31 
xfer b33 f33 
xfer b35 f35 
xfer b37 f37 
xfer b39 f39 
xfer b41 f41 
xfer b43 f43 
xfer b45 f45 
xfer b47 f47 
xfer f1 b1 
xfer f3 b3 
xfer f5 b5 
xfer f7 b7 
xfer f9 b9 
xfer f11 b11 
xfer f13 b13 
xfer f15 b15 
xfer f17 b17 
xfer f19 b19 
xfer f21 b21 
xfer f23 b23 
xfer f25 b25 
xfer f27 b27 
xfer f29 b29 
xfer f31 b31 
rack 2
xfer f33 b31 
xfer f35 b33 
xfer f37 b35 
xfer f39 b37 
xfer f41 b39 
xfer f43 b41 
xfer f45 b43 
xfer f47 b45 
rack 0
xfer f2 b2 
xfer f4 b4 
xfer f6 b6 
xfer f8 b8 
xfer f10 b10 
xfer f12 b12 
xfer f14 b14 
xfer f16 b16 
xfer f18 b18 
xfer f20 b20 
xfer f22 b22 
xfer f24 b24 
xfer f26 b26 
xfer f28 b28 
xfer f30 b30 
xfer f32 b32 
rack 2
xfer f32 b30 
xfer f34 b32 
xfer f36 b34 
xfer f38 b36 
xfer f40 b38 
xfer f42 b40 
xfer f44 b42 
xfer f46 b44 
xfer f48 b46 
rack 0
xfer b32 f32 
xfer b30 f30 
xfer b28 f28 
xfer b26 f26 
xfer b24 f24 
xfer b22 f22 
xfer b20 f20 
xfer b18 f18 
xfer b16 f16 
xfer b14 f14 
xfer b12 f12 
xfer b10 f10 
xfer b8 f8 
xfer b6 f6 
xfer b4 f4 
xfer b2 f2 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
knit - f32 3 
knit - f30 3 
knit - f28 3 
knit - f26 3 
knit - f24 3 
knit - f22 3 
knit - f20 3 
knit - f18 3 
knit - f16 3 
knit - f14 3 
knit - f12 3 
knit - f10 3 
knit - f8 3 
knit - f6 3 
knit - f4 3 
knit - f2 3 
knit + b1 3 
knit + b3 3 
knit + b5 3 
knit + b7 3 
knit + b9 3 
knit + b11 3 
knit + b13 3 
knit + b15 3 
knit + b17 3 
knit + b19 3 
knit + b21 3 
knit + b23 3 
knit + b25 3 
knit + b27 3 
knit + b29 3 
knit + b31 3 
tuck + b32 3 
rack 2
xfer f32 b30 
rack 0
xfer b30 f30 
knit - f30 3 
tuck + b30 3 
rack 2
xfer f30 b28 
rack 0
xfer b28 f28 
knit - f28 3 
tuck + b28 3 
rack 2
xfer f28 b26 
rack 0
xfer b26 f26 
knit - f26 3 
tuck + b26 3 
rack 2
xfer f26 b24 
rack 0
xfer b24 f24 
knit - f24 3 
tuck + b24 3 
rack 2
xfer f24 b22 
rack 0
xfer b22 f22 
knit - f22 3 
tuck + b22 3 
rack 2
xfer f22 b20 
rack 0
xfer b20 f20 
knit - f20 3 
tuck + b20 3 
rack 2
xfer f20 b18 
rack 0
xfer b18 f18 
knit - f18 3 
tuck + b18 3 
rack 2
xfer f18 b16 
rack 0
xfer b16 f16 
knit - f16 3 
tuck + b16 3 
rack 2
xfer f16 b14 
rack 0
xfer b14 f14 
knit - f14 3 
tuck + b14 3 
rack 2
xfer f14 b12 
rack 0
xfer b12 f12 
knit - f12 3 
tuck + b12 3 
rack 2
xfer f12 b10 
rack 0
xfer b10 f10 
knit - f10 3 
tuck + b10 3 
rack 2
xfer f10 b8 
rack 0
xfer b8 f8 
knit - f8 3 
tuck + b8 3 
rack 2
xfer f8 b6 
rack 0
xfer b6 f6 
knit - f6 3 
tuck + b6 3 
rack 2
xfer f6 b4 
rack 0
xfer b4 f4 
knit - f4 3 
tuck + b4 3 
rack 2
xfer f4 b2 
rack 0
xfer b2 f2 
knit - f2 3 
rack 1
xfer f2 b1 
rack 0
knit + b1 3 
tuck - f1 3 
rack 2
xfer b1 f3 
rack 0
xfer f3 b3 
knit + b3 3 
tuck - f3 3 
rack 2
xfer b3 f5 
rack 0
xfer f5 b5 
knit + b5 3 
tuck - f5 3 
rack 2
xfer b5 f7 
rack 0
xfer f7 b7 
knit + b7 3 
tuck - f7 3 
rack 2
xfer b7 f9 
rack 0
xfer f9 b9 
knit + b9 3 
tuck - f9 3 
rack 2
xfer b9 f11 
rack 0
xfer f11 b11 
knit + b11 3 
tuck - f11 3 
rack 2
xfer b11 f13 
rack 0
xfer f13 b13 
knit + b13 3 
tuck - f13 3 
rack 2
xfer b13 f15 
rack 0
xfer f15 b15 
knit + b15 3 
tuck - f15 3 
rack 2
xfer b15 f17 
rack 0
xfer f17 b17 
knit + b17 3 
tuck - f17 3 
rack 2
xfer b17 f19 
rack 0
xfer f19 b19 
knit + b19 3 
tuck - f19 3 
rack 2
xfer b19 f21 
rack 0
xfer f21 b21 
knit + b21 3 
tuck - f21 3 
rack 2
xfer b21 f23 
rack 0
xfer f23 b23 
knit + b23 3 
tuck - f23 3 
rack 2
xfer b23 f25 
rack 0
xfer f25 b25 
knit + b25 3 
tuck - f25 3 
rack 2
xfer b25 f27 
rack 0
xfer f27 b27 
knit + b27 3 
tuck - f27 3 
rack 2
xfer b27 f29 
rack 0
xfer f29 b29 
knit + b29 3 
tuck - f29 3 
rack 2
xfer b29 f31 
rack 0
xfer f31 b31 
knit + b31 3 
drop f32  
drop f31  
drop f30  
drop f29  
drop f28  
drop f27  
drop f26  
drop f25  
drop f24  
drop f23  
drop f22  
drop f21  
drop f20  
drop f19  
drop f18  
drop f17  
drop f16  
drop f15  
drop f14  
drop f13  
drop f12  
drop f11  
drop f10  
drop f9  
drop f8  
drop f7  
drop f6  
drop f5  
drop f4  
drop f3  
drop f2  
drop f1  
drop b1  
drop b2  
drop b3  
drop b4  
drop b5  
drop b6  
drop b7  
drop b8  
drop b9  
drop b10  
drop b11  
drop b12  
drop b13  
drop b14  
drop b15  
drop b16  
drop b17  
drop b18  
drop b19  
drop b20  
drop b21  
drop b22  
drop b23  
drop b24  
drop b25  
drop b26  
drop b27  
drop b28  
drop b29  
drop b30  
drop b32  
xfer b31 f31 
knit + f31 3 
knit - f33 3 
knit - f31 3 
knit + f31 3 
knit + f33 3 
knit - f35 3 
knit - f33 3 
knit - f31 3 
knit + f31 3 
knit + f33 3 
knit + f35 3 
knit - f35 3 
knit - f33 3 
knit - f31 3 
knit + f31 3 
knit + f33 3 
knit + f35 3 
drop f31  
drop f33  
drop f35  
outhook 3  

